front_end:
    resource: "@FrontEndBundle/Controller/"
    type:     annotation
    prefix:   /

back_end:
    resource: "@BackEndBundle/Controller/"
    type:     annotation
    prefix:   /api

app:
    resource: "@AppBundle/Controller/"
    type:     annotation