services:
# BackEnd::VideoService
  backend.video:
    class:  BackEndBundle\Service\VideoService
    arguments: ["@doctrine.orm.default_entity_manager"]
# BackEnd::EventService
  backend.event:
    class:  BackEndBundle\Service\EventService
    arguments: ['@doctrine.orm.default_entity_manager']
# BackEnd::AdminService
  backend.admin:
    class:  BackEndBundle\Service\AdminService
    arguments: ['@doctrine.orm.default_entity_manager']

#    back_end.example:
#        class: BackEndBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
